#!/usr/bin/with-contenv bash

#..make our folders
mkdir -p \
        /config/{www,keys} \
        /run \
        /var/lib/nginx/tmp/client_body \
        /var/tmp/nginx

#..copy config files
[[ ! -f /etc/nginx/nginx.conf ]] && \
        cp /defaults/nginx.conf /etc/nginx/nginx.conf
[[ $(find /config/www -type f | wc -l) -eq 0 ]] && \
        cp /defaults/index.html /config/www/index.html

#..permissions
chown -R abc:abc \
        /config \
        /var/lib/nginx \
        /var/tmp/nginx
chmod -R g+w \
        /config/{nginx,www}
chmod -R 644 /etc/logrotate.d
